Repository CS2103JAN2018-F11-B2/main, pull requests merged in 2018-03, with the labels that each got.

#14 Correction v1.0
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.corrections

#18 Remove browser, include dummy list and minor edits
  README.adoc
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/java/seedu/address/ui/TutorListPanel.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/StudentListPanel.fxml
  src/main/resources/view/TutorListPanel.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/HelpWindowHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: type.enhancement

#19 Enhance find function
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/SearchContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/SearchContainsKeywordsPredicateTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: type.enhancement

#20 TuitionCor related fields
  src/main/java/seedu/address/model/person/Level.java
  src/main/java/seedu/address/model/person/Location.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Subject.java
  src/test/java/seedu/address/model/person/LevelTest.java
  src/test/java/seedu/address/model/person/LocationTest.java
  src/test/java/seedu/address/model/person/SubjectTest.java
Labels: type.enhancement

#23 Update user guide and developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.corrections

#24 Updated AboutUs
  docs/AboutUs.adoc
  docs/images/damithc.jpg
  docs/images/destin.jpg
  docs/images/hongCho.jpg
  docs/images/jiahui.jpg
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
Labels: type.corrections

#26 Corrections for V1.1 and included dummy fields for splitList
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TutorListPanel.fxml
  src/test/java/guitests/guihandles/HelpWindowHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.corrections

#34 Replace dummy text fields with "-"
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.corrections

#56 Developer guide: Sort implementation
  docs/DeveloperGuide.adoc
Labels: type.enhancement

#75 Corrections for V1.2 Fixes #74
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.corrections

#76 SortCommand
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortByGradeCommand.java
  src/main/java/seedu/address/logic/commands/SortByLocationCommand.java
  src/main/java/seedu/address/logic/commands/SortByNameCommand.java
  src/main/java/seedu/address/logic/commands/SortBySubjectCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/SortByGradeComparator.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/Location.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.enhancement, type.epic, type.story

#77 Removed AddCommand, cleared XMLAddressBookStorageTest
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/person/GradeTest.java
  src/test/java/seedu/address/model/person/LocationTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
Labels: type.ongoing
