Repository CS2103JAN2018-F11-B2/main, pull requests merged in 2018-04, with the labels that each got.

#88 Added Junit test for sorting commands. Fixes #87
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/SortByGradeCommand.java
  src/main/java/seedu/address/logic/commands/SortByLocationCommand.java
  src/main/java/seedu/address/logic/commands/SortByNameCommand.java
  src/main/java/seedu/address/logic/commands/SortBySubjectCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/test/java/seedu/address/logic/commands/SortByGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/SortByLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/SortByNameCommandTest.java
  src/test/java/seedu/address/logic/commands/SortBySubjectCommandTest.java
  src/test/java/seedu/address/testutil/SortedClients.java
  src/test/java/seedu/address/testutil/UnsortedClients.java
Labels: type.enhancement

#89 Wc1.4 RemoveCommand and Junit fixes
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/Location.java
  src/main/java/seedu/address/model/person/Subject.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/address/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/address/model/person/GradeTest.java
  src/test/java/seedu/address/model/person/LocationTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.enhancement

#90 Fixes Junit test and minor UserGuide update
  docs/UserGuide.adoc
  src/test/java/seedu/address/testutil/SortedClients.java
  src/test/java/seedu/address/testutil/UnsortedClients.java
Labels: type.corrections

#92 Ranking feature and highlighting feature
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RankComparator.java
  src/main/java/seedu/address/model/person/Client.java
  src/main/java/seedu/address/model/person/MatchContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.enhancement

#94 Collate code for V1.4
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/util/SortByGradeComparator.java
  src/main/java/seedu/address/logic/parser/CloseCommandParser.java
  src/main/java/seedu/address/logic/parser/RestoreCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/java/seedu/address/ui/TutorListPanel.java
  src/test/java/seedu/address/logic/commands/RestoreCommandTest.java
  src/test/java/seedu/address/logic/commands/SwitchCommandTest.java
Labels: type.task

#95 Collate code
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/MatchContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/MatchContainsPersonsPredicate.java
  src/main/java/seedu/address/model/person/SearchContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/ClientCard.java
Labels: type.task

#99 Collate
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/AddClientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Category.java
  src/main/java/seedu/address/model/person/Client.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/Location.java
  src/main/java/seedu/address/model/person/Subject.java
  src/main/java/seedu/address/model/person/UniqueClientList.java
  src/main/java/seedu/address/storage/XmlAdaptedClient.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/test/java/seedu/address/logic/commands/AddClientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/address/model/UniqueClientListTest.java
  src/test/java/seedu/address/model/person/CategoryTest.java
  src/test/java/seedu/address/model/person/GradeTest.java
  src/test/java/seedu/address/model/person/LocationTest.java
  src/test/java/seedu/address/model/person/SubjectTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/ui/ClientCardTest.java
Labels: type.task

#100 UserGuide: Updates
  docs/UserGuide.adoc
Labels: type.corrections

#122 Fix bugs and update test cases
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/MatchFunctionFutureImplementation.png
  docs/images/MatchSequence1.png
  docs/images/MatchSequence2.png
  docs/images/MatchSequence3.png
  docs/images/MatchZeroClient.png
  docs/team/Zhu-Jiahui.adoc
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/MatchCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/MatchContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/MatchCommandTest.java
  src/test/java/seedu/address/logic/parser/MatchCommandParserTest.java
  src/test/java/seedu/address/model/person/MatchContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/MatchContainsPersonsPredicateTest.java
  src/test/java/seedu/address/testutil/MatchedClients.java
  src/test/java/seedu/address/testutil/TypicalCategories.java
  src/test/java/seedu/address/testutil/UnmatchedClients.java
Labels: type.bug, type.task

#123 Editing reported bugs and updating of PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/destin.adoc
  src/main/java/seedu/address/model/person/Client.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
Labels: type.bug, type.optional

#124 Fixes issues, includes PPP and updates for sampledata
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.PNG
  docs/images/Ui.png
  docs/team/limhongcho
  src/main/java/seedu/address/logic/commands/SortByGradeCommand.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandNotAvailableInActiveViewException.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandNotAvailableInClosedViewException.java
  src/main/java/seedu/address/logic/commands/util/GradeUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/util/ListPanelController.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/seedu/address/logic/commands/SwitchCommandTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/SampleDataTest.java
Labels: type.corrections

#127 Fixes Ui.PNG not displaying properly
  README.adoc
Labels: type.corrections

#128 Fixes Ui not displaying correctly
  README.adoc
Labels: type.bug

#129 ReadMe: Fixes Ui not displaying correctly
  README.adoc
Labels: type.bug

#131 Update User guide, developer guide and portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/Zhu-Jiahui.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.documentation

#132 Updates DeveloperGuide, UserGuide, README, AboutUs & PPP
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/hongcho.adoc
Labels: type.documentation

#137 Increase Coverage in Junit and updated PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/destin.adoc
  src/test/java/seedu/address/logic/commands/AddClientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: type.optional
